import React, { useRef, useState } from "react";
import { UserInfoAPI } from "../../../apiCalls";
import useMakeRequest from "../../hooks/useMakeRequest";
import styles from "../../../stylesheets/input.module.css";
import Loader from "../../helpers/Loader";
import {
  rolesDisplayName,
  serverError,
  unKnownError,
} from "../../../helperFuncs";
import Button from "../../helpers/Button";
import { toast } from "react-toastify";
import CheckBoxGroup from "../../helpers/CheckBox/CheckBoxGroup";
import TreeSelect from "rc-tree-select";
import "rc-tree-select/assets/index.css";

const modalRoot = document && document.getElementById("modal-root");

const TreeSelect2 = ({ userId, setCondition }) => {
  const [multipleValue, setMultipleValue] = useState([]);
  const [lv, setLv] = useState([]);
  const nameRef = useRef();

  const [roles, setRoles] = useState([]);
  const [makeRequest, setMakeRequest] = useState(false);

  const handleRoleChange = (items = []) => {
    const newRoles = roles.map((role) => ({
      ...role,
      isIn: items.findIndex((item) => item === role.roleName) !== -1,
    }));
    setRoles(newRoles);
  };

  const gData = [
    {
      title: <span className="item-label">Generic item 2</span>,
      value: "hello",
      children: {
        title: "Hi",
        value: "Hi",
      },
    },
    {
      title: "Hey",
      value: "Hey",
    },
  ];
  const onMultipleChange = (value) => {
    console.log("onMultipleChange", value);
    setMultipleValue(value);
    console.log(value);
  };

  const saveRoles = (e) => {
    setMakeRequest(true);
  };

  const [data, loading] = useMakeRequest(
    UserInfoAPI.getUserRoles,
    200,
    true,
    userId,
    (res) => {
      if (res.status === 200) {
        setRoles(res.data);
      } else if (serverError(res)) return;
    }
  );

  const gdata = [
    {
      id: 2,
      order: 1,
      code: "0",
      title: "ترافیک شهری",
      children: [
        {
          id: 26,
          order: 2,
          code: "1",
          title: "ترمیم و اصلاح و یا نیاز به علائم",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: {
            id: "3a499c06-fba6-48e2-b168-53f318eb6763",
            title: "فرم 1",
            elements: [
              {
                elementType: "header",
                name: "عنوان 1",
                title: "عنوان 1",
                order: 2,
                meta: '{"id":"0e33f6b1-832c-4643-b635-fdf5f727b55b","elementType":"header","elementCategory":"input","props":{"title":"عنوان 1","subTitle":"زیر عنوان","style":{}},"items":[]}',
              },
              {
                elementType: "select",
                name: "موضوع",
                title: "موضوع",
                order: 7,
                meta: '{"id":"c67223f1-ad32-41d6-85ac-370154215bbe","elementType":"select","elementCategory":"input","props":{"label":"موضوع","placeholder":"انتخاب کنید.","editable":false,"style":{"cursor":"pointer"},"options":[{"id":"drop-down-item-1","title":"گزینه 1","value":"option-1"},{"id":"drop-down-item-2","title":"گزینه 2","value":"option-2"},{"id":"drop-down-item-3","title":"گزینه 3","value":"option-3"}]},"items":[]}',
              },
              {
                elementType: "text",
                name: "نام",
                title: "نام",
                order: 1,
                meta: '{"id":"c1566027-5726-442d-81ef-9c3b650a3458","elementType":"text","elementCategory":"input","props":{"label":"نام","placeholder":"متن راهنما","type":"text","editable":true,"disabled":false,"englishOnly":false,"style":{}},"items":[]}',
              },
              {
                elementType: "checkbox",
                name: "تست",
                title: "تست",
                order: 4,
                meta: '{"id":"e562178f-2a7f-4ad9-8312-d951ebc16694","elementType":"checkbox","elementCategory":"input","props":{"label":"تست","disabled":false,"horizontal":true,"defaultSelecteds":[],"options":[{"id":"checkbox-item-1","title":"گزینه 1","value":"option-1"},{"id":"checkbox-item-2","title":"گزینه 2","value":"option-2"},{"id":"checkbox-item-3","title":"گزینه 3","value":"option-3"}]},"items":[]}',
              },
              {
                elementType: "dropzone",
                name: "برچسب",
                title: "برچسب",
                order: 6,
                meta: '{"id":"c665d2c6-f26e-4ea0-a373-f05f0548a542","elementType":"dropzone","elementCategory":"input","props":{"label":"برچسب","placeholder":"فایل را بکشید و اینجا رها کنید."},"items":[]}',
              },
              {
                elementType: "message",
                name: "عنوان پیام",
                title: "عنوان پیام",
                order: 5,
                meta: '{"id":"124899a8-7704-42fa-902d-3079e8c72da4","elementType":"message","elementCategory":"input","props":{"title":"عنوان پیام","description":"توضیحات پیام"},"items":[]}',
              },
              {
                elementType: "textarea",
                name: "عنوان",
                title: "عنوان",
                order: 3,
                meta: '{"id":"29dbc569-848e-4a55-b93d-b02f86caf9e6","elementType":"textarea","elementCategory":"input","props":{"label":"عنوان","placeholder":"توضیح","editable":true,"disabled":false,"englishOnly":false,"style":{}},"items":[]}',
              },
            ],
          },
        },
        {
          id: 27,
          order: 3,
          code: "1",
          title:
            "نیاز به تعمیر و مرمت تابلوهای ترافیکی، راهنما و چراغ راهنمایی و رانندگی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 28,
          order: 4,
          code: "1",
          title: "نصب تابلو راهنمایی، گاردریل",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 29,
          order: 5,
          code: "1",
          title: "نصب چراغ راهنمایی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 30,
          order: 6,
          code: "1",
          title: "مشکل ترافیکی و اصلاح هندسی در محل",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 31,
          order: 7,
          code: "1",
          title: "نیاز به خط کشی خیابان و معبر",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 32,
          order: 8,
          code: "1",
          title: "نصب پل عابر پیاده",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
      ],
      description: "",
      attachmentDescription: "",
      duration: 0,
      responseDuration: null,
      isDeleted: false,
      objectionAllowed: false,
      editingAllowed: true,
      hideMap: false,
      form: null,
    },
    {
      id: 3,
      order: 9,
      code: "1000",
      title: "ایستگاه گاز CNG",
      children: [
        {
          id: 33,
          order: 10,
          code: "1002",
          title: "نیاز به احداث جایگاه سوخت",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 34,
          order: 11,
          code: "1002",
          title: "رفتار نامناسب عوامل جایگاه سوخت",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 35,
          order: 12,
          code: "1002",
          title: "مشکلات مدیریتی جایگاه های سوخت",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
      ],
      description: "",
      attachmentDescription: "",
      duration: 0,
      responseDuration: null,
      isDeleted: false,
      objectionAllowed: false,
      editingAllowed: true,
      hideMap: false,
      form: null,
    },
    {
      id: 4,
      order: 13,
      code: "2000",
      title: "عمرانی و زیر بنایی",
      children: [
        {
          id: 36,
          order: 14,
          code: "2003",
          title: "نصب سرعت گیر",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 37,
          order: 15,
          code: "2003",
          title: "طرح ، اجرا و تصویب تعریض پیاده رو، معابر یا میادین",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 38,
          order: 16,
          code: "2003",
          title: "نصب روشنایی در زیرگذرها و میادین و معابر",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 39,
          order: 17,
          code: "2003",
          title: "مرمت پس از حفاری و نشست",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 40,
          order: 18,
          code: "2003",
          title: "نصب روشنایی در پارکها و فضای سبز",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 41,
          order: 19,
          code: "2003",
          title: "تعمیر روشنایی پارک و معابر",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 42,
          order: 20,
          code: "2003",
          title: "مرمت و تعمیر آبخوری، ابنما پارک و فضاهای عمومی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 43,
          order: 21,
          code: "2003",
          title: "تعمیر وسایل بازی کودکان و بزرگسالان",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 44,
          order: 22,
          code: "2003",
          title: "شعارنویسی و تخریب اموال عمومی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 45,
          order: 23,
          code: "2003",
          title: "جمع آوری تابلوهای غیر مجاز",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 46,
          order: 24,
          code: "2003",
          title: "نصب تابلو نامگذاری معابر",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 47,
          order: 25,
          code: "2003",
          title: "جمع آوری دیوارنویسی و  تبلیغات غیر مجاز",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 48,
          order: 26,
          code: "2003",
          title: "نامگذاری معبر، میدان و ...",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 49,
          order: 27,
          code: "2003",
          title: "تعویض پرچمهای خیابان، میدان و معبر",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 50,
          order: 28,
          code: "2003",
          title: "درخواست رنگ آمیزی و زیباسازی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 51,
          order: 29,
          code: "2003",
          title: "مشکل در آسفالت اجرا شده و شیب بندی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 52,
          order: 30,
          code: "2003",
          title: "مرمت سنگ جدول",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 53,
          order: 31,
          code: "2003",
          title: "تسطیح معبر",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 54,
          order: 32,
          code: "2003",
          title: "لكه گيري، مرمت و آسفالت معابر و پیاده رو",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 55,
          order: 33,
          code: "2003",
          title: "نیاز به روکش آسفالت",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 56,
          order: 34,
          code: "2003",
          title: "نیاز به لایروبی جوی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 57,
          order: 35,
          code: "2003",
          title: "عملیات عمرانی رها شده شهرداری",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 58,
          order: 36,
          code: "2003",
          title: "مرمت و ترمیم دریچه، حفاظ، جدول، پل جوی، پیاده رو و معابر",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
      ],
      description: "",
      attachmentDescription: "",
      duration: 0,
      responseDuration: null,
      isDeleted: false,
      objectionAllowed: false,
      editingAllowed: true,
      hideMap: false,
      form: null,
    },
    {
      id: 5,
      order: 37,
      code: "3000",
      title: "تفکیک و بازیافت",
      children: [
        {
          id: 59,
          order: 38,
          code: "3004",
          title: "تخلیه غیر مجاز پسماندهای عمرانی و ساختمانی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 60,
          order: 39,
          code: "3004",
          title: "اطلاع رسانی مراکز و طریقه جمع آوری زباله های تفکیک شده",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 61,
          order: 40,
          code: "3004",
          title: "تفکیک غیرمجاز زباله",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 62,
          order: 41,
          code: "3004",
          title: "جمع آوری نامناسب زباله های تفکیکی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
      ],
      description: "",
      attachmentDescription: "",
      duration: 0,
      responseDuration: null,
      isDeleted: false,
      objectionAllowed: false,
      editingAllowed: true,
      hideMap: false,
      form: null,
    },
    {
      id: 6,
      order: 42,
      code: "4000",
      title: "ناظرین خاک و نخاله در سطح شهر",
      children: [
        {
          id: 63,
          order: 43,
          code: "4005",
          title: "اخطار جهت جمع آوری پسماندهای  عمرانی و ساختمانی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
      ],
      description: "",
      attachmentDescription: "",
      duration: 0,
      responseDuration: null,
      isDeleted: false,
      objectionAllowed: false,
      editingAllowed: true,
      hideMap: false,
      form: null,
    },
    {
      id: 7,
      order: 44,
      code: "5000",
      title: "ورزش و سلامت",
      children: [
        {
          id: 64,
          order: 45,
          code: "5006",
          title: "تعمیر وسایل ورزشی، تاسیسات و کف پوش مجموعه ورزشی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 65,
          order: 46,
          code: "5006",
          title: "عدم رعایت نظافت در مجموعه ورزشی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 66,
          order: 47,
          code: "5006",
          title: "عدم رعایت نکات امنیتی در مراکز ورزشی بانوان",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 67,
          order: 48,
          code: "5006",
          title: "شرایط نامناسب برگزاری مسابقات در مجموعه ورزشی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 68,
          order: 49,
          code: "5006",
          title: "عدم تخصص داور مسابقات ورزشی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 69,
          order: 50,
          code: "5006",
          title: "عدم توزیع مناسب جوایز مسابقات ورزشی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 70,
          order: 51,
          code: "5006",
          title: "تخلف در مجموعه های ورزشی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 71,
          order: 52,
          code: "5006",
          title: "دریافت مبلغ خارج از تعرف مصوب در مجموعه ورزشی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 72,
          order: 53,
          code: "5006",
          title: "نیاز به بوفه مواد غذایی در مجموعه ورزشی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 73,
          order: 54,
          code: "5006",
          title: "نیاز به امکانات و زمین ورزشی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 74,
          order: 55,
          code: "5006",
          title: "درخواست برگزاری مسابقات ورزشی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
      ],
      description: "",
      attachmentDescription: "",
      duration: 0,
      responseDuration: null,
      isDeleted: false,
      objectionAllowed: false,
      editingAllowed: true,
      hideMap: false,
      form: null,
    },
    {
      id: 8,
      order: 56,
      code: "6000",
      title: "فرهنگی و اجتماعی",
      children: [
        {
          id: 75,
          order: 57,
          code: "6007",
          title: "درخواست برگزاری جشن",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
      ],
      description: "",
      attachmentDescription: "",
      duration: 0,
      responseDuration: null,
      isDeleted: false,
      objectionAllowed: false,
      editingAllowed: true,
      hideMap: false,
      form: null,
    },
    {
      id: 9,
      order: 58,
      code: "7000",
      title: "آموزش شهروندی",
      children: [
        {
          id: 76,
          order: 59,
          code: "7008",
          title: "نیاز به آموزش و فرهنگسازی طرح تفکیک از مبدا",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 77,
          order: 60,
          code: "7008",
          title: "درخواست برگزاری کارگاه آموزشی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 78,
          order: 61,
          code: "7008",
          title: "پیشنهاد مشارکت داوطبانه",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
      ],
      description: "",
      attachmentDescription: "",
      duration: 0,
      responseDuration: null,
      isDeleted: false,
      objectionAllowed: false,
      editingAllowed: true,
      hideMap: false,
      form: null,
    },
    {
      id: 10,
      order: 62,
      code: "8000",
      title: "آتش نشانی",
      children: [
        {
          id: 79,
          order: 63,
          code: "8009",
          title: "تاخیر در اعزام ماشینهای آتش نشانی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 80,
          order: 64,
          code: "8009",
          title: "نیاز به ایستگاه آتش نشانی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 81,
          order: 65,
          code: "8009",
          title: "نیاز به ایستگاه آتش نشانی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
      ],
      description: "",
      attachmentDescription: "",
      duration: 0,
      responseDuration: null,
      isDeleted: false,
      objectionAllowed: false,
      editingAllowed: true,
      hideMap: false,
      form: null,
    },
    {
      id: 11,
      order: 66,
      code: "9000",
      title: "درآمد",
      children: [
        {
          id: 82,
          order: 67,
          code: "9010",
          title: "محاسبات ناصحیح عوارض",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 83,
          order: 68,
          code: "9010",
          title: "عدم صدور قبض عوارض نوسازی سالیانه",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
      ],
      description: "",
      attachmentDescription: "",
      duration: 0,
      responseDuration: null,
      isDeleted: false,
      objectionAllowed: false,
      editingAllowed: true,
      hideMap: false,
      form: null,
    },
    {
      id: 12,
      order: 69,
      code: "10000",
      title: "حمل و نقل عمومی",
      children: [
        {
          id: 84,
          order: 70,
          code: "10011",
          title: "نیاز به تجهیز ایستگاه به سایبان، روشنایی، جی پی اس",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 85,
          order: 71,
          code: "10011",
          title: "مشکلات پایانه های اتوبوس/تاکسی درون شهری",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 86,
          order: 72,
          code: "10011",
          title: "نیاز به ایجاد مسیر اتوبوس/تاکسی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 87,
          order: 73,
          code: "10011",
          title: "مشکل در زمان های حرکت اتوبوسها",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 88,
          order: 74,
          code: "10011",
          title: "نظافت، اصلاح صندلی، رفع خرابی و آلودگی اتوبوس",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 89,
          order: 75,
          code: "10011",
          title: "افزایش تعداد اتوبوس/تاکسی مسیر",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 90,
          order: 76,
          code: "10011",
          title: "افزایش باجه و ساعات کار اتوبوس یا فروش بلیط",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 91,
          order: 77,
          code: "10011",
          title: "عدم توقف اتوبوس/تاکسی برای سوار کردن مسافر",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 92,
          order: 78,
          code: "10011",
          title: "رفتار نامناسب راننده اتوبوس/تاکسی یا فروشنده باجه",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 93,
          order: 79,
          code: "10011",
          title: "جابجایی، اضافه یا کاهش ایستگاه اتوبوس/تاکسی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 94,
          order: 80,
          code: "10011",
          title: "عدم رعایت مسائل اسلامی و اخلاقی در اتوبوس",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 95,
          order: 81,
          code: "10011",
          title: "تعمیر ایستگاه اتوبوس/تاکسی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 96,
          order: 82,
          code: "10011",
          title: "تخلف راننده اتوبوس/تاکسی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 97,
          order: 83,
          code: "10011",
          title: "فرسودگی ناوگان حمل و نقل عمومی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
      ],
      description: "",
      attachmentDescription: "",
      duration: 0,
      responseDuration: null,
      isDeleted: false,
      objectionAllowed: false,
      editingAllowed: true,
      hideMap: false,
      form: null,
    },
    {
      id: 13,
      order: 84,
      code: "11000",
      title: "پایانه های مسافربری",
      children: [
        {
          id: 98,
          order: 85,
          code: "11012",
          title: "عدم رعایت بهداشت و نظافت در محوطه ترمینال",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 99,
          order: 86,
          code: "11012",
          title: "عدم رعایت مسائل بهداشتی، قیمت اجناس در غرفه ها",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 100,
          order: 87,
          code: "11012",
          title: "نظافت نمازخانه ترمینال و تجهیز آن",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 101,
          order: 88,
          code: "11012",
          title: "نظافت و بهداشت محوطه ترمینال و مشکلات پارکینگ خودرو مسافران",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 102,
          order: 89,
          code: "11012",
          title: "عدم رعایت تعرفه پارکینگ ترمینال",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 103,
          order: 90,
          code: "11012",
          title: "نیاز به باربر در ترمینال",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 104,
          order: 91,
          code: "11012",
          title: "اصلاح تابلوهای مسیر در ترمینال",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 105,
          order: 92,
          code: "11012",
          title: "تعمیر آسفالت، پیاده رو و مسیر حرکتی اتوبوس",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 106,
          order: 93,
          code: "11012",
          title: "ضعف مدیریت ترمینال",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 107,
          order: 94,
          code: "11012",
          title: "عدم رعایت نکات بهداشتی و رفاهی در سالن مسافران ترمینال",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 108,
          order: 95,
          code: "11012",
          title: "وجود افراد مزاحم، معتاد و ناسالم در ترمینال",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 109,
          order: 96,
          code: "11012",
          title: "نیاز به تامین پارکسوار",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
      ],
      description: "",
      attachmentDescription: "",
      duration: 0,
      responseDuration: null,
      isDeleted: false,
      objectionAllowed: false,
      editingAllowed: true,
      hideMap: false,
      form: null,
    },
    {
      id: 14,
      order: 97,
      code: "12000",
      title: "آرامستانها",
      children: [
        {
          id: 110,
          order: 98,
          code: "12013",
          title: "تاخیر آمبولانس اموات",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 111,
          order: 99,
          code: "12013",
          title: "هزینه کفن و دفن و قبر",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
      ],
      description: "",
      attachmentDescription: "",
      duration: 0,
      responseDuration: null,
      isDeleted: false,
      objectionAllowed: false,
      editingAllowed: true,
      hideMap: false,
      form: null,
    },
    {
      id: 15,
      order: 100,
      code: "13000",
      title: "اجرائیات سد معبر",
      children: [
        {
          id: 112,
          order: 101,
          code: "13014",
          title: "جمع آوری متکدیان و کودکان خیابانی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 113,
          order: 102,
          code: "13014",
          title:
            "جمع آوری افراد در راه مانده، متواری، بی سرپرست، مجهول الهویه و ...",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 114,
          order: 103,
          code: "13014",
          title: "مزاحمت به جهت سد معبر وسایل برپایی مراسم",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 115,
          order: 104,
          code: "13014",
          title: "مزاحمت به جهت سد معبر کسبه و مغازه داران در محل",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 116,
          order: 105,
          code: "13014",
          title: "سد معبر به جهت حفاری",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 117,
          order: 106,
          code: "13014",
          title: "سد معبر توسط دستفروشان و فروشندگان دوره گرد",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 118,
          order: 107,
          code: "13014",
          title: "ایجاد سد معبر توسط خودرو اسقاطی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
      ],
      description: "",
      attachmentDescription: "",
      duration: 0,
      responseDuration: null,
      isDeleted: false,
      objectionAllowed: false,
      editingAllowed: true,
      hideMap: false,
      form: null,
    },
    {
      id: 16,
      order: 108,
      code: "14000",
      title: "فضای سبز شهری",
      children: [
        {
          id: 119,
          order: 109,
          code: "14015",
          title: "آبیاری، هرس، سمپاشی و رسیدگی به درختان",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 120,
          order: 110,
          code: "14015",
          title: "درخواست کاشت درخت",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 121,
          order: 111,
          code: "14015",
          title: "گزارش قطع درخت",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 122,
          order: 112,
          code: "14015",
          title: "رفع خطر درختان شکسته شده و جمع آوری شاخ و برگ",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 123,
          order: 113,
          code: "14015",
          title: "شستشوی درختان",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
      ],
      description: "",
      attachmentDescription: "",
      duration: 0,
      responseDuration: null,
      isDeleted: false,
      objectionAllowed: false,
      editingAllowed: true,
      hideMap: false,
      form: null,
    },
    {
      id: 17,
      order: 114,
      code: "15000",
      title: "فناوری اطلاعات",
      children: [
        {
          id: 124,
          order: 115,
          code: "15016",
          title: "مشکل پرداخت اینترنتی عوارض نوسازی-مشاغل و خودرو",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
      ],
      description: "",
      attachmentDescription: "",
      duration: 0,
      responseDuration: null,
      isDeleted: false,
      objectionAllowed: false,
      editingAllowed: true,
      hideMap: false,
      form: null,
    },
    {
      id: 18,
      order: 116,
      code: "16000",
      title: "بازرسی",
      children: [
        {
          id: 125,
          order: 117,
          code: "16017",
          title: "شکایت پیمانکار از شهرداری بابت عدم پرداخت صورت وضعیت ها",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 126,
          order: 118,
          code: "16017",
          title: "درخواست یا دریافت رشوه و تخلفات مالی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 127,
          order: 119,
          code: "16017",
          title: "رفتار نادرست مامورین و پرسنل شهرداری",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 128,
          order: 120,
          code: "16017",
          title: "عدم اجرای تعهدات پیمانکار",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 129,
          order: 121,
          code: "16017",
          title: "نارضایتی ازعملکرد کارشناس شهرساز، مامور فنی و بازرس",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
      ],
      description: "",
      attachmentDescription: "",
      duration: 0,
      responseDuration: null,
      isDeleted: false,
      objectionAllowed: false,
      editingAllowed: true,
      hideMap: false,
      form: null,
    },
    {
      id: 19,
      order: 122,
      code: "17000",
      title: "میادین و بازارچه ها",
      children: [
        {
          id: 130,
          order: 123,
          code: "17018",
          title: "نامناسب بودن ساعت کاری",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 131,
          order: 124,
          code: "17018",
          title: "عدم ارائه فاکتور فروش، مغایرت قیمت و رفتار نامناسب",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 132,
          order: 125,
          code: "17018",
          title: "بی کیفیت بودن میوه ها و محصولات ارائه شده در بازار",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 133,
          order: 126,
          code: "17018",
          title: "نامناسب بودن شرایط غرفه های میادین میوه تره بار",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 134,
          order: 127,
          code: "17018",
          title: "عدم وجود اتیکت قیمت و عدم رعایت نرخهای مصوب",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
      ],
      description: "",
      attachmentDescription: "",
      duration: 0,
      responseDuration: null,
      isDeleted: false,
      objectionAllowed: false,
      editingAllowed: true,
      hideMap: false,
      form: null,
    },
    {
      id: 20,
      order: 128,
      code: "18000",
      title: "مشاغل مزاحم شهری",
      children: [
        {
          id: 135,
          order: 129,
          code: "18019",
          title: "رعایت ساعت کار توسط کسبه، کارگاه و ...",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 136,
          order: 130,
          code: "18019",
          title: "وجود مشاغل مزاحم شهری و ایجاد آلودگی صوتی، محیط زیستی و ...",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 137,
          order: 131,
          code: "18019",
          title:
            "مزاحمت همسایگان به دلیل عدم رعایت بهداشت و محیط زیست بافت مسکونی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 138,
          order: 132,
          code: "18019",
          title: "مزاحمت کامیونها، خودروها و آژانسهای کرایه ای",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 139,
          order: 133,
          code: "18019",
          title: "نگهداری و کشتار غیر مجاز حیوانات، پرندگان",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 140,
          order: 134,
          code: "18019",
          title: "عرضه دام غیر بهداشتی و بوی ناشی در این محل",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
      ],
      description: "",
      attachmentDescription: "",
      duration: 0,
      responseDuration: null,
      isDeleted: false,
      objectionAllowed: false,
      editingAllowed: true,
      hideMap: false,
      form: null,
    },
    {
      id: 21,
      order: 135,
      code: "19000",
      title: "زیباسازی",
      children: [
        {
          id: 141,
          order: 136,
          code: "19020",
          title: "نصب پل و دریچه روی جوی و باغچه",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
      ],
      description: "",
      attachmentDescription: "",
      duration: 0,
      responseDuration: null,
      isDeleted: false,
      objectionAllowed: false,
      editingAllowed: true,
      hideMap: false,
      form: null,
    },
    {
      id: 22,
      order: 137,
      code: "20000",
      title: "خدمات شهری",
      children: [
        {
          id: 142,
          order: 138,
          code: "20021",
          title: "شستشوی ایستگاه اتوبوس، گاردریل، جدول",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 143,
          order: 139,
          code: "20021",
          title: "شستشوی معابر",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 144,
          order: 140,
          code: "20021",
          title: "عدم رعایت مسائل فنی و بهداشتی کارگران رفت و روب",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 145,
          order: 141,
          code: "20021",
          title: "انباشته شدن زباله در محل",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 146,
          order: 142,
          code: "20021",
          title: "نیاز به سطل زباله",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 147,
          order: 143,
          code: "20021",
          title: "عدم رعایت و جمع آوری نامناسب زباله توسط خودروهای زباله",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 148,
          order: 144,
          code: "20021",
          title: "مشکل نظافت محل در زمان مناسب",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 149,
          order: 145,
          code: "20021",
          title: "عملکرد نامناسب کارگران جمع آوری زباله",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 150,
          order: 146,
          code: "20021",
          title: "عدم جمع آوری زباله در زمان مناسب",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 151,
          order: 147,
          code: "20021",
          title:
            "عدم رعایت نظافت توسط كسبه و ساکنان محل در هنگام بیرون گذاشتن زباله",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 152,
          order: 148,
          code: "20021",
          title: "جمع آوری مواد خطرناک و زباله بیمارستانی با سایر زباله ها",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 153,
          order: 149,
          code: "20021",
          title: "تعمير و مرمت سطل زباله",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 154,
          order: 150,
          code: "20021",
          title: "نیاز به جمع آوری لاشه حیوانات",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 155,
          order: 151,
          code: "20021",
          title: "نیاز به نظافت معابر سواره و پیاده، فضای سبز معبر و مسیل",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 156,
          order: 152,
          code: "20021",
          title: "نیاز به برف روبی پیاده رو، معبر یا درختان",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 157,
          order: 153,
          code: "20021",
          title: "رفع لغزندگی معابر",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 158,
          order: 154,
          code: "20021",
          title: "پاکسازی جویها و دریچه چاه های جذبی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 159,
          order: 155,
          code: "20021",
          title: "خاک و نخاله بلاصاحب در معابر در حجم کم",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 160,
          order: 156,
          code: "20021",
          title: "وجود حیوانات ناقل بیماری  (سگ های ولگرد)",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
      ],
      description: "",
      attachmentDescription: "",
      duration: 0,
      responseDuration: null,
      isDeleted: false,
      objectionAllowed: false,
      editingAllowed: true,
      hideMap: false,
      form: null,
    },
    {
      id: 23,
      order: 157,
      code: "21000",
      title: "پل عابر پیاده",
      children: [
        {
          id: 161,
          order: 158,
          code: "21022",
          title: "تعمیر پل عابر پیاده و رفع خطر آن",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 162,
          order: 159,
          code: "21022",
          title: "درخواست پله برقی پل عابر پیاده",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
      ],
      description: "",
      attachmentDescription: "",
      duration: 0,
      responseDuration: null,
      isDeleted: false,
      objectionAllowed: false,
      editingAllowed: true,
      hideMap: false,
      form: null,
    },
    {
      id: 24,
      order: 160,
      code: "22000",
      title: "آبگرفتگي ها",
      children: [
        {
          id: 163,
          order: 161,
          code: "22023",
          title: "خسارت وارده به ساختمان ناشی از تاسیسات شهری",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 164,
          order: 162,
          code: "22023",
          title: "درخواست حفر چاه",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 165,
          order: 163,
          code: "22023",
          title: "تخریب شدن چاه جذبی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 166,
          order: 164,
          code: "22023",
          title: "رفع آب گرفتگی معابر و جوی ها در هنگام بارندگی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
      ],
      description: "",
      attachmentDescription: "",
      duration: 0,
      responseDuration: null,
      isDeleted: false,
      objectionAllowed: false,
      editingAllowed: true,
      hideMap: false,
      form: null,
    },
    {
      id: 25,
      order: 165,
      code: "23000",
      title: "اجرائیات ساختمان",
      children: [
        {
          id: 167,
          order: 166,
          code: "23024",
          title: "درخواست حصارکشی و گودبرداری نیمه تمام و رها شده",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 168,
          order: 167,
          code: "23024",
          title: "گزارش ساخت و ساز غیر مجاز در محل",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 169,
          order: 168,
          code: "23024",
          title: "عدم رعایت نکات ایمنی در ساخت و ساز",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 170,
          order: 169,
          code: "23024",
          title: "عملیات عمرانی خارج از ساعت قانونی",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
        {
          id: 171,
          order: 170,
          code: "23024",
          title: "خطر ریزش به علت فرسودگی بافت محل",
          children: [],
          description: "",
          attachmentDescription: "",
          duration: 168,
          responseDuration: 48,
          isDeleted: false,
          objectionAllowed: true,
          editingAllowed: true,
          hideMap: false,
          form: null,
        },
      ],
      description: "",
      attachmentDescription: "",
      duration: 0,
      responseDuration: null,
      isDeleted: false,
      objectionAllowed: false,
      editingAllowed: true,
      hideMap: false,
      form: null,
    },
  ];

  const [, saveLoading] = useMakeRequest(
    UserInfoAPI.saveRoles,
    200,
    makeRequest,
    { roles: roles },
    (res) => {
      setMakeRequest(false);
      setCondition(false);
      modalRoot.classList.remove("active");
      if (res.status === 200) {
      } else if (serverError(res)) return;
      else if (unKnownError(res)) return;
    },
    userId
  );

  const adata = [
    {
      label: "Table name",
      value: "Table name",
      children: [
        {
          label: "Student",
          value: "Student",
          children: [
            { label: "Id", value: "Id" },
            { label: "Name", value: "Name" },
          ],
        },
      ],
    },
    {
      label: "Condition",
      value: "Condition",
      children: [
        {
          label: ">",
          value: ">",
        },
        {
          label: "<",
          value: "<",
        },
      ],
    },
  ];
  return (
    <>
      <div>
        <TreeSelect
          style={{ width: "400px" }}
          getPopupContainer={(triggerNode) => triggerNode.parentNode}
          transitionName="rc-tree-select-dropdown-slide-up"
          choiceTransitionName="rc-tree-select-selection__choice-zoom"
          // dropdownStyle={true}
          dropdownStyle={{ maxHeight: 200, overflow: "auto", zIndex: 1500 }}
          placeholder={<i>please select</i>}
          //allowClear
          treeDefaultExpandAll="true"
          multiple
          value={multipleValue}
          treeData={gdata}
          treeLine
          allowClear
          treeNodeFilterProp="title"
          //filterTreeNode={false}
          onChange={onMultipleChange}
          onFocus={false}
        />
      </div>
    </>
  );
};

export default TreeSelect2;
