name: build

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  BuildAndDocker:
    env: 
      RUNNER_TOOL_CACHE: /toolcache
      ACTIONS_STEP_DEBUG: true
      PNPM_ENABLE_LOGS: true

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js 20.17.0
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build Project
        run: |
          CI=false SKIP_PREFLIGHT_CHECK=true pnpm build --verbose

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            razava/shahrbin-jame-admin
          tags: |
            type=ref,event=branch
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: . 
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
